package model;

// Generated 24 août 2016 20:46:12 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Devicesinuse generated by hbm2java
 */
@Entity
@Table(name = "devicesinuse", catalog = "molisdb")
public class Devicesinuse implements java.io.Serializable {

	private DevicesinuseId id;
	private Date dateDebut;
	private Date heureDebut;
	private Date dateFin;
	private Date heureFin;
	private String description;

	public Devicesinuse() {
	}

	public Devicesinuse(DevicesinuseId id, Date dateDebut, Date heureDebut,
			Date dateFin, Date heureFin) {
		this.id = id;
		this.dateDebut = dateDebut;
		this.heureDebut = heureDebut;
		this.dateFin = dateFin;
		this.heureFin = heureFin;
	}

	public Devicesinuse(DevicesinuseId id, Date dateDebut, Date heureDebut,
			Date dateFin, Date heureFin, String description) {
		this.id = id;
		this.dateDebut = dateDebut;
		this.heureDebut = heureDebut;
		this.dateFin = dateFin;
		this.heureFin = heureFin;
		this.description = description;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idDevice", column = @Column(name = "id_device", nullable = false)),
			@AttributeOverride(name = "idUser", column = @Column(name = "id_user", nullable = false)) })
	public DevicesinuseId getId() {
		return this.id;
	}

	public void setId(DevicesinuseId id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_debut", nullable = false, length = 10)
	public Date getDateDebut() {
		return this.dateDebut;
	}

	public void setDateDebut(Date dateDebut) {
		this.dateDebut = dateDebut;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "heure_debut", nullable = false, length = 8)
	public Date getHeureDebut() {
		return this.heureDebut;
	}

	public void setHeureDebut(Date heureDebut) {
		this.heureDebut = heureDebut;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_fin", nullable = false, length = 10)
	public Date getDateFin() {
		return this.dateFin;
	}

	public void setDateFin(Date dateFin) {
		this.dateFin = dateFin;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "heure_fin", nullable = false, length = 8)
	public Date getHeureFin() {
		return this.heureFin;
	}

	public void setHeureFin(Date heureFin) {
		this.heureFin = heureFin;
	}

	@Column(name = "description", length = 30)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
