package model;


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "participation", catalog = "molisdb", uniqueConstraints = @UniqueConstraint(columnNames = "id_reunion"))
public class Participation {
	
	private ParticipationId participationId;
	private Users user;
	private Reunion reunion;
	private int duree;
	
	public Participation() {
	}
	
	

	public Participation(ParticipationId participationId, Users user,
			Reunion reunion, int duree) {
		super();
		this.participationId = participationId;
		this.user = user;
		this.reunion = reunion;
		this.duree = duree;
	}


	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id_reunion", column = @Column(name = "id_reunion", nullable = false)),
			@AttributeOverride(name = "id_user", column = @Column(name = "id_user", nullable = false)) })
	public ParticipationId getParticipationId() {
		return participationId;
	}

	public void setParticipationId(ParticipationId participationId) {
		this.participationId = participationId;
	}

	@Column(name="duree",nullable=false)
	public int getDuree() {
		return duree;
	}

	public void setDuree(int duree) {
		this.duree = duree;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_user", nullable = false, insertable = false, updatable = false)
	public Users getUser() {
		return user;
	}

	public void setUser(Users user) {
		this.user = user;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_reunion", nullable = false, insertable = false, updatable = false)
	public Reunion getReunion() {
		return reunion;
	}

	public void setReunion(Reunion reunion) {
		this.reunion = reunion;
	}	
	
	
}
