package model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "reunion", catalog = "molisdb", uniqueConstraints = @UniqueConstraint(columnNames = "id_reunion"))
public class Reunion implements java.io.Serializable {

	private Integer reunionId;
	private Date dateReunion;
	private String description;

	public Reunion() {
	}

	public Reunion(Date dateReunion, String description) {
		this.dateReunion=dateReunion;
		this.description=description;
	}

	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id_reunion", unique = true, nullable = false)
	public Integer getReunionId() {
		return reunionId;
	}

	public void setReunionId(Integer reunionId) {
		this.reunionId = reunionId;
	}

	@Column(name = "date_reunion", unique = true, nullable = false, length = 80)
	public Date getDateReunion() {
		return dateReunion;
	}

	public void setDateReunion(Date dateReunion) {
		this.dateReunion = dateReunion;
	}

	@Column(name = "description", unique = true, nullable = false, length = 300)
	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	
	

}
