package src.main.java.model;

// Generated 24 août 2016 20:46:12 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * DevicesinuseId generated by hbm2java
 */
@Embeddable
public class DevicesinuseId implements java.io.Serializable {

	private int idDevice;
	private int idUser;

	public DevicesinuseId() {
	}

	public DevicesinuseId(int idDevice, int idUser) {
		this.idDevice = idDevice;
		this.idUser = idUser;
	}

	@Column(name = "id_device", nullable = false)
	public int getIdDevice() {
		return this.idDevice;
	}

	public void setIdDevice(int idDevice) {
		this.idDevice = idDevice;
	}

	@Column(name = "id_user", nullable = false)
	public int getIdUser() {
		return this.idUser;
	}

	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DevicesinuseId))
			return false;
		DevicesinuseId castOther = (DevicesinuseId) other;

		return (this.getIdDevice() == castOther.getIdDevice())
				&& (this.getIdUser() == castOther.getIdUser());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdDevice();
		result = 37 * result + this.getIdUser();
		return result;
	}

}
